### ISSUE TITLE
[Keadex Mina Bug] Incorrect rendering of diagram on docusaurus

### ISSUE THREAD

**Issue by Roggstars** [keadex/web-apps#4]
First of all: **thank you** for building and maintaining this collection of apps and libraries. I really like it!

**Describe the bug**
I have followed your description on the [docusaurus-plugin-mina website](https://www.npmjs.com/package/@keadex/docusaurus-plugin-mina) on a fresh docusaurus website (I have created that from their [create-docusaurus](https://docusaurus.io/docs#fast-track) tool. However, the website does not seem to be able to render the diagram (see attached screenshot below). I also tried your example project for the docusaurus plugin on GitHub, which worked fine. Is there a specific version that I need to install of a specific dependency (docusaurus, Node, ...)?

I also noticed that I had to manually install `@yaireo/tagify` and `buffer` before I was able to run the project at all. Maybe those are not provided through the plugins even though they are required? I had that issue both on your GitHub example project and when setting up Docusaurus from scratch. While this might be a separate problem (and I am happy to open another issue for that if you think it is necessary) I wanted to provide that for context still.

**To Reproduce**
1. Create a new Docusaurus website, following the [Fast Track](https://docusaurus.io/docs#fast-track) instructions.
2. Perform [instructions](https://www.npmjs.com/package/@keadex/docusaurus-plugin-mina) to add the docusaurus-plugin-mina.
3. Manually install `@yaireo/tagify` and `buffer`.
4. Run Docusaurus website and navigate to where you included the sample diagram.

**Expected behavior**
The sample diagram is rendered successfully (as it does in the example provided on your [GitHub page](https://github.com/keadex/keadex/tree/main/examples/mina-docusaurus-example)).

**Screenshots**
<img width="1512" alt="Screenshot" src="https://github.com/user-attachments/assets/2c000bed-2067-420d-b38d-b6eb9c3a9178">

**Comment by keadex** [comment]
@Roggstars you're correct, there were missing dependencies. In addition, there were a missing step in the Docusaurus plugin documentation: you need to import the Mina React CSS in your custom Docusaurus CSS file. The documentation has now been updated: check it [here](https://www.npmjs.com/package/@keadex/docusaurus-plugin-mina#import-the-mina-react-css).

Please download the latest versions of [@keadex/docusaurus-plugin-mina](https://www.npmjs.com/package/@keadex/docusaurus-plugin-mina) and [@keadex/mina-react](https://www.npmjs.com/package/@keadex/mina-react) and be sure to check [this step](https://www.npmjs.com/package/@keadex/docusaurus-plugin-mina#import-the-mina-react-css).

I also updated the [examples](https://github.com/keadex/keadex/tree/main/examples) in the repo.
