### ISSUE TITLE
[Keadex Mina Bug] Webpack Loader Issue Causes Docusaurus Build Failure

### ISSUE THREAD

**Issue by fPrager** [keadex/web-apps#6]
First of all, thank you for the great work on mina-react and the docusaurus-plugin-mina. 

**Describe the bug**

I encountered a bug when using the docusaurus-plugin-mina with the mina-react component in a Docusaurus project. When I try to build the site with Docusaurus, the build process fails due to a Webpack loader issue. My assumption is, that it's related to the WebAssembly (.wasm) asset.

The error message suggests that Webpack is unable to process a file because the appropriate loader is not configured. This prevents the Docusaurus site from building successfully.

**To Reproduce**
1. checkout the example project you provide: [mina-docusaurus-example](https://github.com/keadex/keadex/tree/main/examples/mina-docusaurus-example)
2. run `yarn install`
3. run `yarn build`
 
**Expected behavior**
The build is successful and the static page is generated in the build folder.

**Actual behaviour**
The build fails with this error:

```
[ERROR] Error: Unable to build website for locale en.
    at tryToBuildLocale (/path/to/project/node_modules/@docusaurus/core/lib/commands/build.js:54:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /path/to/project/node_modules/@docusaurus/core/lib/commands/build.js:65:9
    at async mapAsyncSequential (/path/to/project/node_modules/@docusaurus/utils/lib/jsUtils.js:21:24)
    at async Command.build (/path/to/project/node_modules/@docusaurus/core/lib/commands/build.js:63:5) {
  [cause]: Error: Failed to compile due to Webpack errors.
  Module parse failed: Unexpected character '' (1:0)
  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  (Source code omitted for this binary file)
      at /path/to/project/node_modules/@docusaurus/core/lib/webpack/utils.js:153:24
      at /path/to/project/node_modules/webpack/lib/MultiCompiler.js:629:14
      at processQueueWorker (/path/to/project/node_modules/webpack/lib/MultiCompiler.js:566:6)
      at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

**Additional context**
- The issue seems to be present from the beginning; I tried the first committed version of the mina-docusaurus-sample-project and it fails as well with the same error.
- Interestingly, your [mina react-app example ](https://github.com/keadex/keadex/tree/main/examples/mina-react-example)builds successfully, which suggests that there might be a standard Webpack loader involved in a the [react-app-rewired](https://github.com/timarney/react-app-rewired) project that is missing in Docusaurus.
- I added more loggin to the webpack exception (`ModuleParseError` from [here](https://github.com/webpack/webpack/blob/27cf3e59f5f289dfc4d76b7a1df2edbc4e651589/lib/ModuleParseError.js#L16)) and the `type` of the file is "`javascript/auto`" and the logged `source` looks much like a webassembly file

**Comment by keadex** [comment]
@fPrager the issue were related to an incompatibility of the Mina plugin with the SSR. 

To solve the issue, the `MinaReact` component must be included in the `<BrowserOnly>` [Docusaurus component](https://docusaurus.io/docs/docusaurus-core#browseronly). 
[Here](https://raw.githubusercontent.com/keadex/keadex/main/examples/mina-docusaurus-example/docs/intro.md) you can find an example.

Then, the Webpack configuration was fixed in version `1.9.0` of `@keadex/docusaurus-plugin-mina`. You can download the latest version from [npm](https://www.npmjs.com/package/@keadex/docusaurus-plugin-mina).

You can try again by downloading the updated [example](https://github.com/keadex/keadex/tree/main/examples/mina-docusaurus-example), which includes the latest version of the plugin and the fixed import of the diagram.

**Comment by fPrager** [comment]
Incredible reaction time! We integrated the fix right away and are now able to see beautiful diagrams in our docs.
Thanks a lot!

**Comment by giacomosimmi** [comment]
I'm glad it works now! If you like Mina or Keadex projects, the best way to contribute is to star this repo and share it with your colleagues/friends 🙂

**Comment by keadex** [comment]
I'm glad it works now! If you like Mina or Keadex projects, the best way to contribute is to star this repo and share it with your colleagues/friends 🙂
